### PR TITLE
WIP: DisplayGroup: allow commit() to fail for a few times

### PR DESCRIPTION
**Pull request by peat-psuwit**
Commit() can fails for a transient reason. For example, if a client
disconnects between the content list is submitted and hwc->set() is
called, it will fails.

Usually, the next call should fix the problem, but if it happens more
than 3 times in a row, it may indicates that the problem is, in fact,
not transient. In this case, we'll forward the exception up the call
stack, which will then terminate the server.

### CODE REVIEW

**Comment by peat-psuwit** [comment]
This bug report might shed some light on why Mir behaves the way it did: https://bugs.launchpad.net/mir/+bug/1498550

**Comment by mariogrip** [comment]
I'm not sure it's a good idea to ignore `hwc->prepeare` calls as they would indicate invalid state, also we could en up in a endless "flip-flop" situation where one content commit fails adding to the counter and next being successful resetting the counter and next one fails and so on. As the system-compositor will flip between contents this may happen

**Comment by peat-psuwit** [comment]
Actually, SurfaceFlinger _does_ also ignore hwc.prepare().

https://android.googlesource.com/platform/frameworks/native/+/android-7.1.1_r28/services/surfaceflinger/SurfaceFlinger_hwc1.cpp#1267

But on the flip-flop thing, how does system-compositor flip between contents? My initial rationale is that if committing fails intermittently, it might be better not to crash the server as at least _some_ frames are displayed.

(And BTW in which way can the state be invalid? What's in the state?)

**Comment by peat-psuwit** [comment]
Closed in favor of #17.

**Pull request closed without merging**
