### PR TITLE
missing create_rendering_platform symbol

### PR DESCRIPTION
**Pull request by APokorny**
The symbol file for graphics platforms was changed.

### CODE REVIEW

**Comment by nfsprodriver** [comment]
xenial_-_edge_-_mir32 branch isn't working yet at all so shall I merge it to get the changes beeing built?

**Comment by APokorny** [comment]
did I mess up the ci configuration - why is it lacking android-24 and android-24-caf?
I wanted to propose another fix necessary to support unity8

**Comment by APokorny** [comment]
Ah I could also make a pull request against master

**Comment by nfsprodriver** [comment]
I think it fails because apt is only search through the current branch name. There's no mir-0.32.x branch to find the android-headers package.

**Comment by APokorny** [comment]
yes please merge

**Comment by mariogrip** [comment]
Just the pr that was stale, the branch should build fine

**Pull request merged**
